site_name: Niagara Data Platform
copyright: Maintained by <a href="http://alvincjin.github.io">Alvin Jin</a>
theme: readthedocs

pages:
    - Home: index.md
    - Installation: install.md
    - Data Streaming: stream.md
    - Event Sourcing & CQRS: escqrs.md
    - Machine Learning: ml.md
    - About: about.md
